### ISSUE TITLE
Q: How to gRPC client for UserAccess

### ISSUE THREAD

**Issue by Tridy** [countincognito/Company.Dapr#3]
I am trying to create a client that will call UserAccess service started locally, and to create a client according to the link from Microsoft I will need to import .proto files into the client application. and .proto files are not used in the solution.

How do I call a running Company.Access.User.Service endpoint from Postman, for instance?

When I start it, the browser address is: 

https://localhost:7236/

and the reply is:

`Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909`

**Comment by countincognito** [comment]
This sample is interface-driven, so you don't need .proto files. You create your gRPC contracts using interface and DTO contracts.

To create a gRPC client for UserAccess you can use the client builder found here:

https://github.com/countincognito/Company.Dapr/blob/develop/src/Company.Engine.Registration.Service/Program.cs#L29

If you don't want to use the TrackingContext, then just follow the code here:

https://github.com/countincognito/Company.Dapr/blob/develop/src/Company.iFX.Dapr/TrackingContextDaprClient.cs

And remove the TrackingContextGrpcInterceptor.

Note: the App ID you use in the client must match the App ID used by the service for Dapr to route the traffic.

Hope this helps.
