### ISSUE TITLE
2 MicroserviceProfile.cs files

### ISSUE THREAD

**Issue by Tridy** [countincognito/Company.Dapr#4]
I was wondering about these 2  mapping files:

A. src/Company.Microservice.Membership.Service/MicroserviceProfile.cs
B. src/Company.Microservice.Membership/MicroserviceProfile.cs

since these are identical except for the namespace, would it be okay to have a link from A to B instead? Or are there any scenarios when they would be different?

**Comment by countincognito** [comment]
Yes, it would be fine to have a shared mapping profile in this instance.

The purpose of the two projects is to demonstrate how one can either have a fully in-proc service (combining all the libraries in one executable), or a distributed service (making remote calls over the wire), and the project code will still be very similar.
