### ISSUE TITLE
A message improvement

### ISSUE THREAD

**Issue by Tridy** [countincognito/Company.Dapr#5]
in UseCaseFactory.cs

https://github.com/countincognito/Company.Dapr/blob/65f7b34b0683b26b4d22c0d8dfd11cd73064d886/src/Company.iFX.Proxy/UseCaseFactory.cs#L37C88-L37C108

```
Type? useCaseInterfaceType = Assembly.GetAssembly(typeof(TService))?.GetType(useCaseTypeName);
Debug.Assert(useCaseInterfaceType is not null, $@"Could not find the type {useCaseInterfaceType}");
```

For the line with Debug.Assert, it looks like `useCaseInterfaceType` is always going to be null, so I think the meaning there was to use `useCaseTypeName` instead. Is this right?

**Comment by countincognito** [comment]
Well spotted. I have made the recommended change.
