### ISSUE TITLE
Q: OpenTelemetry and Logging

### ISSUE THREAD

**Issue by Tridy** [countincognito/Company.Dapr#7]
I am trying to figure out if hoe the part with the  OpenTelemetry works. I wonder what kind of effect `iFX.Telelmetry` has on `iFX.Logging`, and if I should use Telemetry or not. I do not know how the internals of it work, and what the role of it is in the project.

Is it so that `Telemetry` adds additional/automatic aspects of Performance, Statistics, etc, while `Logging` deals with the manual logs that I am doing from the components? I cannot find how the data from Telemetry gets into Loggin. Perhaps I misunderstand how it works. Could you give me a hint, please?

**Comment by countincognito** [comment]
Yes, you have pretty much understood how it works.

The logging goes to the Seq instance whereas the telemetry information goes to the Zipkin instance. There is some additional telemetry spans which passes the CallChainId to Zipkin, but that is only so you can cross reference the logging to the telemetry more easily.

Hope this helps.
